apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-go
  template:
    metadata:
      labels:
        app: hello-world-go
    spec:
      containers:
      - name: hello-world-go
        image: hello-world-go:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-go-service
spec:
  selector:
    app: hello-world-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer